<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="18" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="861933" started-at="2017-11-29T09:31:54Z" finished-at="2017-11-29T09:46:16Z">
    <groups>
    </groups>
    <test name="Sikuli HIS2" duration-ms="333720" started-at="2017-11-29T09:31:54Z" finished-at="2017-11-29T09:37:28Z">
      <class name="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS">
        <test-method status="PASS" signature="dieukienDauTien()[pri:0, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="dieukienDauTien" is-config="true" duration-ms="34517" started-at="2017-11-29T16:31:54Z" finished-at="2017-11-29T16:32:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dieukienDauTien -->
        <test-method status="FAIL" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1()[pri:1, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1" duration-ms="62108" started-at="2017-11-29T16:32:29Z" finished-at="2017-11-29T16:33:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Tiếp nhận Bệnh nhân không thành công !]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Tiếp nhận Bệnh nhân không thành công !
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1(TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2()[pri:2, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2" duration-ms="92452" started-at="2017-11-29T16:33:31Z" finished-at="2017-11-29T16:35:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3()[pri:3, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3" duration-ms="32063" started-at="2017-11-29T16:35:04Z" finished-at="2017-11-29T16:35:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4()[pri:4, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4" duration-ms="29419" started-at="2017-11-29T16:35:36Z" finished-at="2017-11-29T16:36:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5()[pri:5, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5" duration-ms="16132" started-at="2017-11-29T16:36:05Z" finished-at="2017-11-29T16:36:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6()[pri:6, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6" duration-ms="18740" started-at="2017-11-29T16:36:21Z" finished-at="2017-11-29T16:36:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7()[pri:7, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7" duration-ms="45766" started-at="2017-11-29T16:36:40Z" finished-at="2017-11-29T16:37:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7 -->
        <test-method status="PASS" signature="ketThucLuong1()[pri:0, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS@6e1ec318]" name="ketThucLuong1" is-config="true" duration-ms="2502" started-at="2017-11-29T16:37:26Z" finished-at="2017-11-29T16:37:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ketThucLuong1 -->
      </class> <!-- TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS -->
    </test> <!-- Sikuli HIS2 -->
    <test name="Sikuli HIS3 " duration-ms="528182" started-at="2017-11-29T09:37:28Z" finished-at="2017-11-29T09:46:16Z">
      <class name="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS">
        <test-method status="PASS" signature="dieukienDauTien()[pri:0, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="dieukienDauTien" is-config="true" duration-ms="35008" started-at="2017-11-29T16:37:28Z" finished-at="2017-11-29T16:38:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dieukienDauTien -->
        <test-method status="FAIL" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1()[pri:1, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1" duration-ms="61709" started-at="2017-11-29T16:38:03Z" finished-at="2017-11-29T16:39:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Tiếp nhận Bệnh nhân không thành công !]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Tiếp nhận Bệnh nhân không thành công !
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2()[pri:2, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2" duration-ms="21958" started-at="2017-11-29T16:39:05Z" finished-at="2017-11-29T16:39:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3()[pri:3, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3" duration-ms="44284" started-at="2017-11-29T16:39:27Z" finished-at="2017-11-29T16:40:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4()[pri:4, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4" duration-ms="26872" started-at="2017-11-29T16:40:11Z" finished-at="2017-11-29T16:40:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5()[pri:5, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5" duration-ms="19783" started-at="2017-11-29T16:40:38Z" finished-at="2017-11-29T16:40:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6()[pri:6, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6" duration-ms="25704" started-at="2017-11-29T16:40:58Z" finished-at="2017-11-29T16:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7()[pri:7, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7" duration-ms="54076" started-at="2017-11-29T16:41:23Z" finished-at="2017-11-29T16:42:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7 -->
        <test-method status="PASS" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_8()[pri:8, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_8" duration-ms="59429" started-at="2017-11-29T16:42:18Z" finished-at="2017-11-29T16:43:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_8 -->
        <test-method status="FAIL" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_9()[pri:9, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_9" duration-ms="74261" started-at="2017-11-29T16:43:17Z" finished-at="2017-11-29T16:44:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Không tìm thấy bệnh nhân với mã số Bênh nhân 1711000530]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Không tìm thấy bệnh nhân với mã số Bênh nhân 1711000530
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_9(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:379)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_9 -->
        <test-method status="FAIL" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_10()[pri:10, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_10" duration-ms="28787" started-at="2017-11-29T16:44:31Z" finished-at="2017-11-29T16:45:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Không thể lưu kết quả Kết Luận cuối cùng của bác sĩ , đã gặp sự cố !]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Không thể lưu kết quả Kết Luận cuối cùng của bác sĩ , đã gặp sự cố !
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_10(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:395)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_10 -->
        <test-method status="FAIL" signature="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_11()[pri:11, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_11" duration-ms="71707" started-at="2017-11-29T16:45:00Z" finished-at="2017-11-29T16:46:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Không tìm thấy thông tin người cần thanh toán viện phí ! ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Không tìm thấy thông tin người cần thanh toán viện phí ! 
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_11(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_11 -->
        <test-method status="PASS" signature="ketThucLuong1()[pri:0, instance:TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS@5abca1e0]" name="ketThucLuong1" is-config="true" duration-ms="4604" started-at="2017-11-29T16:46:12Z" finished-at="2017-11-29T16:46:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ketThucLuong1 -->
      </class> <!-- TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS -->
    </test> <!-- Sikuli HIS3  -->
  </suite> <!-- Suite -->
</testng-results>
