<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NVHA" name="Sikuli HIS3 " tests="11" failures="4" timestamp="29 Nov 2017 09:46:16 GMT" time="528.182" errors="0">
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1" time="61.709" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS">
    <failure type="java.lang.AssertionError" message="Tiếp nhận Bệnh nhân không thành công !">
      <![CDATA[java.lang.AssertionError: Tiếp nhận Bệnh nhân không thành công !
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:147)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1 -->
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2" time="21.958" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3" time="44.284" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4" time="26.872" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5" time="19.783" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6" time="25.704" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7" time="54.076" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_8" time="59.429" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_9" time="74.261" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS">
    <failure type="java.lang.AssertionError" message="Không tìm thấy bệnh nhân với mã số Bênh nhân 1711000530">
      <![CDATA[java.lang.AssertionError: Không tìm thấy bệnh nhân với mã số Bênh nhân 1711000530
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_9(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:379)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_9 -->
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_10" time="28.787" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS">
    <failure type="java.lang.AssertionError" message="Không thể lưu kết quả Kết Luận cuối cùng của bác sĩ , đã gặp sự cố !">
      <![CDATA[java.lang.AssertionError: Không thể lưu kết quả Kết Luận cuối cùng của bác sĩ , đã gặp sự cố !
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_10(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:395)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_10 -->
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_11" time="71.707" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS">
    <failure type="java.lang.AssertionError" message="Không tìm thấy thông tin người cần thanh toán viện phí ! ">
      <![CDATA[java.lang.AssertionError: Không tìm thấy thông tin người cần thanh toán viện phí ! 
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_11(TestLuongTiepNhanBNDichVu_ThuTienSau_CLS.java:434)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_11 -->
</testsuite> <!-- Sikuli HIS3  -->
